    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DangNhapTK;
import Model.HoaDonNhap;
import Model.Sach;
import Table.TableHDNhap;
import Table.TableSach;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyHoaDonNhap extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel hd = null;
    ArrayList<HoaDonNhap> ds = new ArrayList<>();

    /**
     * Creates new form QuanLyHoaDon
     */
    public void layHDN() {
        String sql = "select * from HoaDonNhap";

        
        Statement stm;
        try {
            stm = (Statement) conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                String maHDN = rs.getString("maHDN");
                String maSach = rs.getString("maSach");
                String maNV = rs.getString("maNV");
                String ngayNhap = rs.getString("ngayNhap");
                int soLuongN = rs.getInt("soLuongN");
                float donGiaN = rs.getFloat("donGiaN");
                float thanhTienN = rs.getFloat("thanhTienN");
                HoaDonNhap hd = new HoaDonNhap(maHDN, maSach, maNV, ngayNhap, soLuongN, donGiaN, thanhTienN);
                ds.add(hd);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public List<String> layMaSach(){
        List<String> danhSach = new ArrayList<>();
        try{
            
            String sql = "select maSach from Sach";
            Statement stm = (Statement) conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                String maSach = rs.getString("maSach");
                danhSach.add(maSach);
            }
                       
            }catch(Exception e){
                e.printStackTrace();
               }
        return danhSach;
    }
    public void xuatMaSach(){
        List<String> maSach = layMaSach();
        jcmbMaSach.removeAllItems();
        for(String string: maSach){
            jcmbMaSach.addItem(string);
        }
    }
    public QuanLyHoaDonNhap() {
        initComponents();
        layHDN();
        loadTable();
    }

    public void loadTable() {
        jtblHoaDonNhap.setModel(new TableHDNhap(ds));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHoaDonNhap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfNgayLap = new javax.swing.JTextField();
        jtfDonGia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfSoLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfThanhTien = new javax.swing.JTextField();
        jbtnQuayLai = new javax.swing.JButton();
        jbtnThemHoaDon = new javax.swing.JButton();
        jbtnTimHD = new javax.swing.JButton();
        jcmbMaSach = new javax.swing.JComboBox<>();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN NHẬP");

        jtblHoaDonNhap.setBackground(new java.awt.Color(102, 255, 102));
        jtblHoaDonNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sách", "Mã nhân viên", "Số lượng", "Đơn giá", "Thành tiền", "Ngày lập"
            }
        ));
        jScrollPane1.setViewportView(jtblHoaDonNhap);
        if (jtblHoaDonNhap.getColumnModel().getColumnCount() > 0) {
            jtblHoaDonNhap.getColumnModel().getColumn(3).setResizable(false);
            jtblHoaDonNhap.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã hóa đơn nhập:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã nhân viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã sách:");

        jtfMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaNVActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày nhập:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Đơn giá nhập:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng nhập:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thành tiền:");

        jbtnQuayLai.setBackground(new java.awt.Color(102, 255, 102));
        jbtnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnQuayLai.setText("Quay lại");
        jbtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuayLaiActionPerformed(evt);
            }
        });

        jbtnThemHoaDon.setBackground(new java.awt.Color(102, 255, 102));
        jbtnThemHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThemHoaDon.setText("Thêm hóa đơn");
        jbtnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemHoaDonActionPerformed(evt);
            }
        });

        jbtnTimHD.setBackground(new java.awt.Color(102, 255, 102));
        jbtnTimHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTimHD.setText("Tìm kiếm");
        jbtnTimHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimHDActionPerformed(evt);
            }
        });

        jbtnSua.setBackground(new java.awt.Color(102, 255, 102));
        jbtnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.setMaximumSize(new java.awt.Dimension(148, 29));
        jbtnSua.setMinimumSize(new java.awt.Dimension(148, 29));
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setBackground(new java.awt.Color(102, 255, 102));
        jbtnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jbtnQuayLai)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNgayLap, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmbMaSach, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                    .addComponent(jtfMaHD, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jbtnThemHoaDon)
                                .addGap(94, 94, 94)
                                .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfThanhTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(jbtnTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnQuayLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMaHD)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaNVActionPerformed

    private void jbtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuayLaiActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnQuayLaiActionPerformed

    private void jbtnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemHoaDonActionPerformed
        String sql = "Insert into  HoaDonNhap values (?,?,?,?,?,?,?)";
        
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtfMaHD.getText());
            pst.setString(2, (String) jcmbMaSach.getSelectedItem());
            pst.setString(3, jtfMaNV.getText());
            pst.setString(7, jtfNgayLap.getText());
            pst.setFloat(5, Float.valueOf(jtfDonGia.getText()));
            pst.setInt(4, Integer.valueOf(jtfSoLuong.getText()));
            pst.setFloat(6, Float.valueOf(jtfThanhTien.getText()));
            pst.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Đã có mã hóa đơn hoặc nhân viên không tồn tại");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Nhập thiếu dữ liệu");
        }
        ds.clear();
        layHDN();
        loadTable();
    }//GEN-LAST:event_jbtnThemHoaDonActionPerformed

    private void jbtnTimHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimHDActionPerformed
        ArrayList<HoaDonNhap> timKiem = new ArrayList<>();
        for (HoaDonNhap hd : ds) {
            if (jtfMaHD.getText().equals(hd.getMaHDN())) {
                timKiem.add(hd);
                jtfDonGia.setText(String.valueOf(hd.getDonGiaN()));
                jtfMaNV.setText(hd.getMaNV());
                jtfNgayLap.setText(hd.getNgayNhap());
                jtfSoLuong.setText(String.valueOf(hd.getSoLuong()));
                jtfThanhTien.setText(String.valueOf(hd.getThanhTien()));
                for (int i = 0; i < jcmbMaSach.getItemCount(); i++) {
                    if (jcmbMaSach.getItemAt(i).toString().equals(hd.getMaSach())) {
                        jcmbMaSach.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }
        jtblHoaDonNhap.setModel(new TableHDNhap(timKiem));
    }//GEN-LAST:event_jbtnTimHDActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        String sql = "Update  HoaDonNhap set maSach=? ,maNV=? ,soLuongN=? ,donGiaN=?, thanhTienN=? , ngayNhap=? where maHDN=?";
         
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(7, jtfMaHD.getText());
            pst.setString(1, (String) jcmbMaSach.getSelectedItem());
            pst.setFloat(4, Float.valueOf(jtfDonGia.getText()));
            pst.setString(2, jtfMaNV.getText());
            pst.setInt(3, Integer.valueOf(jtfSoLuong.getText()));
            pst.setFloat(5, Float.valueOf(jtfThanhTien.getText()));
            pst.setString(6, jtfNgayLap.getText());
            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        ds.clear();
        layHDN();
        loadTable();
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        String sql = "Delete  HoaDonNhap where maHDN=?";
      
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtfMaHD.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        ds.clear();
        layHDN();
        loadTable();
    }//GEN-LAST:event_jbtnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDonNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnQuayLai;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThemHoaDon;
    private javax.swing.JButton jbtnTimHD;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcmbMaSach;
    private javax.swing.JTable jtblHoaDonNhap;
    private javax.swing.JTextField jtfDonGia;
    private javax.swing.JTextField jtfMaHD;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfNgayLap;
    private javax.swing.JTextField jtfSoLuong;
    private javax.swing.JTextField jtfThanhTien;
    // End of variables declaration//GEN-END:variables
}
