/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connect.ConnectionDatabase;
import Model.HoaDonNhap;
import Model.HoaDonXuat;
import Table.TableHDNhap;
import Table.TableHDXuat;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyHoaDonXuat extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel hd = null;
    ArrayList<HoaDonXuat> ds = new ArrayList<>();
    
    public void layHDX() {
        String sql = "select * from HoaDonXuat";

         Connection conn = new ConnectionDatabase().getConn();
        Statement stm;
        try {
            stm = (Statement) conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                String maHDX = rs.getString("maHDX");
                String maSach = rs.getString("maSach");
                String maNV = rs.getString("maNV");
                String ngayXuat = rs.getString("ngayXuat");
                int soLuongX = rs.getInt("soLuongX");
                float donGiaX = rs.getFloat("donGiaX");
                float thanhTienX = rs.getFloat("thanhTienX");
                HoaDonXuat hd = new HoaDonXuat(maHDX, maSach, maNV, ngayXuat, soLuongX, donGiaX, thanhTienX);
                ds.add(hd);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public QuanLyHoaDonXuat() {
        initComponents();
        layHDX();
        loadTable();
    }
     public void loadTable() {
        jtblHoaDonXuat.setModel(new TableHDXuat(ds));
    }
      public List<String> layMaSach(){
        List<String> danhSach = new ArrayList<>();
        try{
            Connection conn = new ConnectionDatabase().getConn();
            String sql = "select maSach from Sach";
            Statement stm = (Statement) conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                String maSach = rs.getString("maSach");
                danhSach.add(maSach);
            }
                       
            }catch(Exception e){
                e.printStackTrace();
               }
        return danhSach;
    }
    public void xuatMaSach(){
        List<String> maSach = layMaSach();
        jcmbMaSach.removeAllItems();
        for(String string: maSach){
            jcmbMaSach.addItem(string);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnQuayLai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHoaDonXuat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnThem = new javax.swing.JButton();
        jbtnTimKiem = new javax.swing.JButton();
        jtfMaHDX = new javax.swing.JTextField();
        jtfMaNV = new javax.swing.JTextField();
        jtfNgayXuat = new javax.swing.JTextField();
        jtfDonGiaX = new javax.swing.JTextField();
        jtfSoLuongX = new javax.swing.JTextField();
        jtfThanhTien = new javax.swing.JTextField();
        jcmbMaSach = new javax.swing.JComboBox<>();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnQuayLai.setBackground(new java.awt.Color(102, 255, 102));
        jbtnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnQuayLai.setText("Quay lại");
        jbtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuayLaiActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN XUẤT");

        jtblHoaDonXuat.setBackground(new java.awt.Color(102, 255, 102));
        jtblHoaDonXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblHoaDonXuat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtblHoaDonXuatAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jtblHoaDonXuat);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã hóa đơn xuất:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã sách:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày xuất:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Đơn giá xuất:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng xuất:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thành tiền:");

        jbtnThem.setBackground(new java.awt.Color(102, 255, 102));
        jbtnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThem.setText("Thêm hóa đơn");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnTimKiem.setBackground(new java.awt.Color(102, 255, 102));
        jbtnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTimKiem.setText("Tìm kiếm");
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jtfDonGiaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDonGiaXActionPerformed(evt);
            }
        });

        jcmbMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbMaSachActionPerformed(evt);
            }
        });

        jbtnSua.setBackground(new java.awt.Color(102, 255, 102));
        jbtnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setBackground(new java.awt.Color(102, 255, 102));
        jbtnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtnQuayLai)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jbtnThem)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNgayXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jtfMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMaHDX, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmbMaSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDonGiaX)
                                    .addComponent(jtfSoLuongX)
                                    .addComponent(jtfThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnQuayLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfMaHDX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDonGiaX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSoLuongX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuayLaiActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnQuayLaiActionPerformed

    private void jtfDonGiaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDonGiaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDonGiaXActionPerformed

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
         String sql = "Insert into  HoaDonXuat values (?,?,?,?,?,?,?)";
        Connection conn = new ConnectionDatabase().getConn();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtfMaHDX.getText());
            pst.setString(2, (String) jcmbMaSach.getSelectedItem());
            pst.setString(3, jtfMaNV.getText());
            pst.setString(7, jtfNgayXuat.getText());
            pst.setFloat(5, Float.valueOf(jtfDonGiaX.getText()));
            pst.setInt(4, Integer.valueOf(jtfSoLuongX.getText()));
            pst.setFloat(6, Float.valueOf(jtfThanhTien.getText()));
            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Đã có mã hóa đơn hoặc mã nhân viên không tồn tại");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Nhập thiếu dữ liệu");
        }
        ds.clear();
        layHDX();
        loadTable();
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        String sql = "Update  HoaDonXuat set maSach=? ,maNV=? ,soLuongX=? ,donGiaX=?, thanhTienX=? , ngayXuat=? where maHDX=?";
        Connection conn = new ConnectionDatabase().getConn();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(7, jtfMaHDX.getText());
            pst.setString(1, (String) jcmbMaSach.getSelectedItem());
            pst.setFloat(4, Float.valueOf(jtfDonGiaX.getText()));
            pst.setString(2, jtfMaNV.getText());
            pst.setInt(3, Integer.valueOf(jtfSoLuongX.getText()));
            pst.setFloat(5, Float.valueOf(jtfThanhTien.getText()));
            pst.setString(6, jtfNgayXuat.getText());
            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(Level.SEVERE, null, ex);
        }
        ds.clear();
        layHDX();
        loadTable();
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
       String sql = "Delete  HoaDonXuat where maHDX=?";
      Connection conn = new ConnectionDatabase().getConn();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtfMaHDX.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        ds.clear();
        layHDX();
        loadTable();
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        ArrayList<HoaDonXuat> timKiem = new ArrayList<>();
        for (HoaDonXuat hd : ds) {
            if (jtfMaHDX.getText().equals(hd.getMaHDX())) {
                timKiem.add(hd);
                jtfDonGiaX.setText(String.valueOf(hd.getDonGiaX()));
                jtfMaNV.setText(hd.getMaNV());
                jtfNgayXuat.setText(hd.getNgayXuat());
                jtfSoLuongX.setText(String.valueOf(hd.getSoLuongX()));
                jtfThanhTien.setText(String.valueOf(hd.getThanhTien()));
                for (int i = 0; i < jcmbMaSach.getItemCount(); i++) {
                    if (jcmbMaSach.getItemAt(i).toString().equals(hd.getMaSach())) {
                        jcmbMaSach.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }
        jtblHoaDonXuat.setModel(new TableHDXuat(timKiem));
    }//GEN-LAST:event_jbtnTimKiemActionPerformed

    private void jtblHoaDonXuatAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtblHoaDonXuatAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblHoaDonXuatAncestorAdded

    private void jcmbMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbMaSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDonXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnQuayLai;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnTimKiem;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcmbMaSach;
    private javax.swing.JTable jtblHoaDonXuat;
    private javax.swing.JTextField jtfDonGiaX;
    private javax.swing.JTextField jtfMaHDX;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfNgayXuat;
    private javax.swing.JTextField jtfSoLuongX;
    private javax.swing.JTextField jtfThanhTien;
    // End of variables declaration//GEN-END:variables
}
