/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Model.TaiKhoan;
import Model.ThongKe;
import Table.TableTaiKhoan;
import Table.TableThongKe;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ThongKeSach extends javax.swing.JFrame {

    private final String FILE_PATH = "ThongKeSach.txt";
    DefaultTableModel hd = null;
    ArrayList<ThongKe> ds = new ArrayList<>();

    public void layThongKe() {
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                String maTK = parts[0];
                String maSach = parts[1];
                String ngayTK = parts[2];
                int soLuongTon = Integer.parseInt(parts[3]);
                ThongKe tke = new ThongKe(maTK, maSach, ngayTK, soLuongTon);
                ds.add(tke);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi đọc dữ liệu từ tệp: " + e.getMessage());
        }
    }

    public List<String> layMaSach() {
         List<String> danhSach = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                String maSach = parts[1]; // Giả sử mã sách nằm ở vị trí thứ 2 trong mỗi dòng của tệp
                danhSach.add(maSach);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi đọc dữ liệu từ tệp: " + e.getMessage());
        }
        return danhSach;
    }

    public void xuatMaSach() {
        List<String> maSach = layMaSach();
        jcmbMaSach.removeAllItems();
        for (String string : maSach) {
            jcmbMaSach.addItem(string);
        }
    }

    public void loadTable() {
        jtblThongKe.setModel(new TableThongKe(ds));
    }

    public ThongKeSach() {
        initComponents();
        layThongKe();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnQuayLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblThongKe = new javax.swing.JTable();
        jbtnThem = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jbtnTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfMaTK = new javax.swing.JTextField();
        jtfNgayTK = new javax.swing.JTextField();
        jtfSoLuongTon = new javax.swing.JTextField();
        jcmbMaSach = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THỐNG KÊ SÁCH");

        jbtnQuayLai.setBackground(new java.awt.Color(102, 255, 102));
        jbtnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnQuayLai.setText("Quay lại");
        jbtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuayLaiActionPerformed(evt);
            }
        });

        jtblThongKe.setBackground(new java.awt.Color(102, 255, 102));
        jtblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblThongKe);

        jbtnThem.setBackground(new java.awt.Color(102, 255, 102));
        jbtnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnSua.setBackground(new java.awt.Color(102, 255, 102));
        jbtnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setBackground(new java.awt.Color(102, 255, 102));
        jbtnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnTimKiem.setBackground(new java.awt.Color(102, 255, 102));
        jbtnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTimKiem.setText("Tìm kiếm");
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã thống kê:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ngày thống kê:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Số lượng tồn:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mã sách:");

        jtfNgayTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNgayTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jbtnQuayLai)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNgayTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMaTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSoLuongTon)
                            .addComponent(jcmbMaSach, 0, 161, Short.MAX_VALUE))
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jbtnTimKiem)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnQuayLai))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jtfSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jcmbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jtfNgayTK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtfMaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuayLaiActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnQuayLaiActionPerformed

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
         try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH, true))) {
        String maThongKe = jtfMaTK.getText();
        String maSach = (String) jcmbMaSach.getSelectedItem();
        String ngayThongKe = jtfNgayTK.getText();
        int soLuongTon = Integer.parseInt(jtfSoLuongTon.getText());
        
        // Ghi dữ liệu vào tệp
        writer.write(String.format("%s,%s,%s,%d", maThongKe, maSach, ngayThongKe, soLuongTon));
        writer.newLine();
        
        JOptionPane.showMessageDialog(null, "Thêm dữ liệu thành công!");
        
        // Làm mới danh sách và bảng hiển thị
        ds.clear();
        layThongKe();
        loadTable();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi thêm dữ liệu vào tệp: " + e.getMessage());
    }
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        try {
        List<String> lines = Files.readAllLines(Paths.get(FILE_PATH));
        String maThongKe = jtfMaTK.getText();
        String maSach = (String) jcmbMaSach.getSelectedItem();
        String ngayThongKe = jtfNgayTK.getText();
        int soLuongTon = Integer.parseInt(jtfSoLuongTon.getText());
        
        // Tìm dòng chứa thông tin của mã thống kê cần sửa
        for (int i = 0; i < lines.size(); i++) {
            String[] parts = lines.get(i).split(",");
            if (parts[0].equals(maThongKe)) {
                parts[1] = maSach;
                parts[2] = ngayThongKe;
                parts[3] = Integer.toString(soLuongTon);
                lines.set(i, String.join(",", parts));
                break;
            }
        }
        
        // Ghi lại dữ liệu vào tệp
        Files.write(Paths.get(FILE_PATH), lines);
        
        JOptionPane.showMessageDialog(null, "Sửa dữ liệu thành công!");
        
        // Làm mới danh sách và bảng hiển thị
        ds.clear();
        layThongKe();
        loadTable();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi sửa dữ liệu trong tệp: " + e.getMessage());
    }
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
         String maThongKe = jtfMaTK.getText();
    try {
        List<String> lines = Files.readAllLines(Paths.get(FILE_PATH));
        
        // Lọc ra các dòng không chứa mã thống kê cần xóa
        lines = lines.stream().filter(line -> !line.startsWith(maThongKe)).collect(Collectors.toList());
        
        // Ghi lại dữ liệu vào tệp
        Files.write(Paths.get(FILE_PATH), lines);
        
        JOptionPane.showMessageDialog(null, "Xóa dữ liệu thành công!");
        
        // Làm mới danh sách và bảng hiển thị
        ds.clear();
        layThongKe();
        loadTable();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi xóa dữ liệu từ tệp: " + e.getMessage());
    }
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        ArrayList<ThongKe> timKiem = new ArrayList<>();
        for (ThongKe s : ds) {
            if (jtfMaTK.getText().equals(s.getMaTK())) {
                timKiem.add(s);
                jtfNgayTK.setText(s.getNgayTK());
                jtfSoLuongTon.setText(String.valueOf(s.getSoLuongTon()));
                for (int i = 0; i < jcmbMaSach.getItemCount(); i++) {
                    if (jcmbMaSach.getItemAt(i).toString().equals(s.getMaSach())) {
                        jcmbMaSach.setSelectedIndex(i);
                        break;
                    }
                }

            }
        }
        jtblThongKe.setModel(new TableThongKe(timKiem));
    }//GEN-LAST:event_jbtnTimKiemActionPerformed

    private void jtfNgayTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNgayTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNgayTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnQuayLai;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnTimKiem;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcmbMaSach;
    private javax.swing.JTable jtblThongKe;
    private javax.swing.JTextField jtfMaTK;
    private javax.swing.JTextField jtfNgayTK;
    private javax.swing.JTextField jtfSoLuongTon;
    // End of variables declaration//GEN-END:variables
}
